export const REQUEST_COURSE = 'REQUEST_COURSE';
export const REQUEST_COURSE_SUCCESS = 'REQUEST_COURSE_SUCCESS';
export const REQUEST_COURSE_FAILURE = 'REQUEST_COURSE_FAILURE';

export const REQUEST_COURSE = 'CREATE_COURSE';
export const REQUEST_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const REQUEST_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';

export const REQUEST_COURSE = 'EDIT_COURSE';
export const REQUEST_COURSE_SUCCESS = 'EDIT_COURSE_SUCCESS';
export const REQUEST_COURSE_FAILURE = 'EDIT_COURSE_FAILURE';

export const REQUEST_COURSE = 'CREATE_REVIEW';
export const REQUEST_COURSE_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const REQUEST_COURSE_FAILURE = 'CREATE_REVIEW_FAILURE';