export const REQUEST_COURSE_LIST = 'REQUEST_COURSE_LIST';
export const REQUEST_COURSE_LIST_SUCCESS = 'REQUEST_COURSE_LIST_SUCCESS';
export const REQUEST_COURSE_LIST_FAILURE = 'REQUEST_COURSE_LIST_FAILURE';
